const country=document.getElementById('country'),pack=document.getElementById('package'),confirmed=document.getElementById('confirmed'),pay=document.getElementById('pay');
const plans={
 occlusion:{name:'Occlusion Made Easy',count:'October 3, 10:00 a.m. New York time (EDT)',india:2999,regional:39,standard:199,group:'single',rule:'No prerequisite. Join October 3 to qualify for Vertical Dimension on October 17.'},
 vertical:{name:'Vertical Dimension with FMR',count:'October 17, 10:00 a.m. New York time (EDT)',india:2999,regional:39,standard:199,group:'single',rule:'Requires our Occlusion module. Previous attendees already qualify.'},
 rehab:{name:'Occlusion & Rehabilitation',count:'October 3 + October 17, both at 10:00 a.m. New York time (EDT)',india:5499,regional:69,standard:369,group:'two',rule:'Two lectures covering the foundations of our full-mouth rehabilitation teaching. No All-on-X commitment.'},
 implants:{name:'Implants: Foundations to Restoration',count:'Two lectures. Standalone module.',india:5499,regional:69,standard:369,group:'implants',rule:'Independent entry. Attend foundations and surgery, then restoration. No Occlusion or Vertical Dimension prerequisite.'},
 allx:{name:'All-on-X module',count:'Two lectures. For eligible previous attendees.',india:5499,regional:69,standard:369,group:'allx',rule:'Requires completion of our Occlusion and Vertical Dimension modules. Includes both All-on-X lectures.'},
 allxpath:{name:'All-on-X Pathway',count:'Occlusion + Vertical Dimension + both All-on-X lectures',india:9999,regional:129,standard:669,group:'allxpath',rule:'Four lectures. Includes both prerequisite modules and the complete All-on-X module.'},
 full:{name:'Complete Programme',count:'All four modules, six lectures',india:12999,regional:169,standard:849,group:'full',rule:'Includes Occlusion, Vertical Dimension, both All-on-X lectures and both Implant lectures.'}
};
let countries=[],links={},message='';
const tier=c=>c.code==='IN'?'india':c.tier;
const currency=c=>c.code==='IN'?'INR':'USD';
const money=(n,c)=>new Intl.NumberFormat(c.code==='IN'?'en-IN':'en-US',{style:'currency',currency:currency(c),maximumFractionDigits:0}).format(n);
const fee=(plan,c)=>plan[tier(c)]==null?'Bundle fee on enquiry':money(plan[tier(c)],c);
function selected(){return countries.find(c=>c.code===country.value)}
function payment(){
 const c=selected(),plan=plans[pack.value],checkoutTier=c&&tier(c),href=checkoutTier&&links[checkoutTier]?.[plan.group];
 const prerequisite=['vertical','allx'].includes(pack.value),enabled=Boolean(href&&(!prerequisite||confirmed.checked));
 confirmed.closest('label').style.display=prerequisite?'flex':'none';document.getElementById('confirmation-text').textContent=pack.value==='vertical'?'I have completed STABLE Academy’s Occlusion module.':'I have completed STABLE Academy’s Occlusion and Vertical Dimension modules.';
 pay.style.display=href||!c?'':'none';
 const help=document.getElementById('payment-help');
 if(!c){pay.href='#registration-country';pay.textContent='Select your country to continue';pay.removeAttribute('aria-disabled');pay.style.opacity='1';pay.style.pointerEvents='auto';help.textContent='Select your country at the top of this form to see the right fee and payment step.';return;}
 if(enabled){const target=new URL(href);target.searchParams.set('client_reference_id','stable_'+pack.value+'_'+c.code.toLowerCase()+'_2026');pay.href=target.href;pay.removeAttribute('aria-disabled')}else{pay.removeAttribute('href');pay.setAttribute('aria-disabled','true')}
 pay.textContent=href?'Pay '+fee(plan,c)+' securely':'Email your enrolment enquiry';pay.style.opacity=enabled?'1':'.45';pay.style.pointerEvents=enabled?'auto':'none';
 help.textContent=!href?'Direct checkout is unavailable for this selection. Please use the enquiry below.':!enabled?(pack.value==='vertical'?'Confirm you have completed our Occlusion module to continue.':'Confirm you have completed both prerequisite modules to continue.'):'Your secure Stripe checkout is ready. Stripe collects your full name and email.';
}
function render(){document.getElementById('registration-country').value=country.value;const c=selected(),p=plans[pack.value],known=c&&['india','regional','standard'].includes(tier(c));document.getElementById('enquiry-details').open=Boolean(c&&!links[tier(c)]?.[p.group]);const amount=known?fee(p,c):'Confirm your tuition';document.getElementById('amount').textContent=c?amount:'Select your country';document.getElementById('prerequisite').textContent=p.rule;document.getElementById('selected-country').textContent=c?'Country of primary practice: '+c.name:'Select your country in the form to see your fee.';document.getElementById('regional-note').textContent=known?(tier(c)==='india'?'Your tuition is shown and billed in Indian rupees.':tier(c)==='regional'?'Your regional tuition is shown and billed in US dollars. Choose 1, 2, 4 or 6 lectures and pay directly.':'Your tuition is shown and billed in US dollars.'):'Select your country to see the applicable fee. If it is missing, contact us.';document.getElementById('price-list').replaceChildren();for(const key of ['occlusion','rehab','implants','allx','allxpath','full']){const item=plans[key],row=document.createElement('div');row.className='plan-row';const copy=document.createElement('div'),h=document.createElement('h3'),d=document.createElement('p'),cost=document.createElement('span');h.textContent=key==='occlusion'?'1 lecture — Occlusion or Vertical Dimension':key==='rehab'?'2 lectures — Occlusion + Vertical Dimension':key==='implants'?'2 lectures — Implants':key==='allx'?'2 lectures — All-on-X module':key==='allxpath'?'4 lectures — All-on-X pathway':'6 lectures — Complete programme';d.textContent=key==='occlusion'?'Vertical Dimension requires previous Occlusion.':item.count;cost.className='plan-price';cost.textContent=known?fee(item,c):'Select country';copy.append(h,d);row.append(copy,cost);document.getElementById('price-list').append(row)}message='Hello Dr Parmar, I would like to enrol in '+p.name+'. '+(known?'My tuition is '+amount+' ('+currency(c)+'). ':'')+(c?'I primarily practise in '+c.name+'. ':'')+'Please confirm my session time and send me the next steps to enrol.';updateEnquiry();document.getElementById('status').textContent='';confirmed.checked=false;payment();}
function simplifyChoices(){
 const labels={occlusion:'1 lecture — Occlusion Made Easy',vertical:'1 lecture — Vertical Dimension with FMR (previous Occlusion required)',rehab:'2 lectures — Occlusion + Vertical Dimension',implants:'2 lectures — Implants: Foundations to Restoration',allx:'2 lectures — All-on-X module (prerequisites required)',allxpath:'4 lectures — All-on-X pathway',full:'6 lectures — Complete programme'};
 for(const option of pack.options)option.textContent=labels[option.value]||option.textContent;
 const tuitionIntro=document.querySelector('#tuition h2+p');if(tuitionIntro)tuitionIntro.textContent='Everyone receives the same teaching and materials. Select your country, then choose 1, 2, 4 or 6 lectures. Your exact fee and secure payment button appear immediately.';
 const registerIntro=document.querySelector('#register .split>div>p:nth-of-type(2)');if(registerIntro)registerIntro.textContent='Choose your country, choose 1, 2, 4 or 6 lectures, then pay securely. Your exact regional fee appears immediately. Vertical-only and All-on-X-only bookings require the listed previous modules.';
 const regionalSummary=Array.from(document.querySelectorAll('#tuition details')).find(item=>item.querySelector('summary')?.textContent.includes('regional tuition'));if(regionalSummary){const paragraphs=regionalSummary.querySelectorAll('p');if(paragraphs[0])paragraphs[0].textContent='India: ₹2,999 for one lecture, ₹5,499 for two, ₹9,999 for four, or ₹12,999 for six. Eligible regional countries: US$39 for one lecture, US$69 for two, US$129 for four, or US$169 for six. The US and comparable high-income countries use standard tuition. Everyone receives the same teaching and materials.';if(paragraphs[1])paragraphs[1].textContent='Your fee is based on where you primarily practise. Select your country and proceed directly to the matching secure Stripe checkout.'}
}
function updateEnquiry(){
 const question=document.getElementById('learning-question').value.trim(),name=document.getElementById('attendee-name').value.trim(),email=document.getElementById('attendee-email').value.trim();
 const contact=(name?' My name is '+name+'.':'')+(email?' My email is '+email+'.':'');
 const consent=document.getElementById('community-opt-in').checked?' I would also like STABLE Academy community news and future course updates by email.':' Please send course-related emails only.';
 const text=message+contact+(question?' I would like to understand: '+question:'')+consent;
 document.getElementById('enquiry').textContent=text;
 document.getElementById('email-enquiry').href='mailto:drparmardds@gmail.com?subject='+encodeURIComponent('STABLE Academy enrolment: '+plans[pack.value].name)+'&body='+encodeURIComponent(text);
}
function validContact(){for(const id of ['attendee-name','attendee-email']){const el=document.getElementById(id);if(!el.value.trim()||!el.checkValidity()){el.reportValidity();el.focus();return false}}return true}
for(const id of ['attendee-name','attendee-email'])document.getElementById(id).addEventListener('input',updateEnquiry);
document.getElementById('community-opt-in').addEventListener('change',updateEnquiry);
document.getElementById('email-enquiry').addEventListener('click',event=>{if(!validContact())event.preventDefault()});
document.getElementById('registration-country').addEventListener('change',event=>{country.value=event.target.value;render()});
document.getElementById('learning-question').addEventListener('input',updateEnquiry);
country.addEventListener('change',render);pack.addEventListener('change',render);confirmed.addEventListener('change',payment);
document.querySelectorAll('.pick').forEach(a=>a.addEventListener('click',()=>{pack.value=a.dataset.plan;render()}));
document.getElementById('copy').addEventListener('click',async()=>{if(!validContact())return;try{await navigator.clipboard.writeText(document.getElementById('enquiry').textContent);document.getElementById('status').textContent='Copied. Open Instagram and paste your enquiry.'}catch{document.getElementById('status').textContent='Please select and copy the enquiry above.'}});
async function init(){simplifyChoices();try{const [cr,lr]=await Promise.all([fetch('assets/countries.json'),fetch('assets/payment-links.json')]);if(!cr.ok||!lr.ok)throw Error('Unavailable');countries=(await cr.json()).countries;links=await lr.json();for(const c of countries){const o=document.createElement('option');o.value=c.code;o.textContent=c.name;country.append(o)}const other=document.createElement('option');other.value='OTHER';other.textContent='My country is not listed';country.append(other);countries.push({code:'OTHER',name:'a country not listed',tier:'enquiry'});document.getElementById('registration-country').replaceChildren(...Array.from(country.options,o=>o.cloneNode(true)));render()}catch{render();document.getElementById('status').textContent='Tuition options could not load. Please contact Dr Parmar to confirm your fee.'}}
init();
